org: coconamatata
app: test
service: videoService

plugins:
    - serverless-offline

provider:
    name: aws
    runtime: nodejs20.x
    region: ap-northeast-2

functions:
    api:
        handler: handler.handler
        events:
            - http:
                  path: upload
                  method: post
